### ISSUE TITLE
OS X 10.9.5 Library Versions

### ISSUE THREAD

**Issue by artjomg** [RishiGupta12/serial-communication-manager#3]
Hi,

I am on mac OS X 10.9.5  and use System.out.println(scm.getLibraryVersions()) to get the versions of the libs. However it looks like there is a mismatch between the Java and native lib.

Java lib version: 1.0.3
Native lib version: 1.0.2

Are the Versions compatible?

Thanx,
Rtg

**Comment by RishiGupta12** [comment]
Version have been used for info purpose only. They do not interfere with operations in any way.
